"""renamed price to cost

Revision ID: b2862d082b5b
Revises: 6c24367e39ba
Create Date: 2026-08-30 19:56:26.174135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2862d082b5b'
down_revision: Union[str, Sequence[str], None] = '6c24367e39ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "books",
        "price",
        new_column_name="cost"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "books",
        "cost",
        new_column_name="price"
    )
    # ### end Alembic commands ###
